### ISSUE TITLE
App crashes on CENTOS

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/create-supertokens-app#47]
```
create-supertokens-app (v0.0.22) lets you quickly get started with using SuperTokens!

Choose your tech stack and the authentication method, we will create a working project that uses SuperTokens for you.


? What is your app called? localapp
? Choose a frontend framework (Visit our documentation for integration with other frameworks): React

? Choose a backend framework (Visit our documentation for integration with other frameworks):
Node.js
? What type of authentication do you want to use? Email Password

✅ Finished setting up folder structure!

✅ Setup complete!


To start the application run the following command:

cd localapp
npm run start
```

After running `npm run start`, the following error shows up:
```
0 verbose cli /opt/alt/alt-nodejs16/root/usr/bin/node /opt/alt/alt-nodejs16/root/usr/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@8.15.0
2 info using node@v16.17.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 6ms
5 timing config:load:file:/opt/alt/alt-nodejs16/root/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/mygrsolu/localapp/localapp/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/home/mygrsolu/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/opt/alt/alt-nodejs16/root/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 17ms
19 timing npm:load:configload Completed in 17ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm run start:frontend
23 verbose argv "run" "start:frontend"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 5ms
27 verbose logfile logs-max:10 dir:/home/mygrsolu/.npm/_logs
28 verbose logfile /home/mygrsolu/.npm/_logs/2023-01-02T16_57_31_192Z-debug-0.log
29 timing npm:load:logFile Completed in 6ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 31ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing command:run Completed in 11ms
36 verbose stack TypeError: Cannot read properties of undefined (reading 'stdin')
36 verbose stack     at promiseSpawnUid (/opt/alt/alt-nodejs16/root/usr/lib/node_modules/npm/node_modules.bundled/@npmcli/promise-spawn/lib/index.js:70:18)
36 verbose stack     at promiseSpawn (/opt/alt/alt-nodejs16/root/usr/lib/node_modules/npm/node_modules.bundled/@npmcli/promise-spawn/lib/index.js:14:10)
36 verbose stack     at runScriptPkg (/opt/alt/alt-nodejs16/root/usr/lib/node_modules/npm/node_modules.bundled/@npmcli/run-script/lib/run-script-pkg.js:68:13)
36 verbose stack     at runScript (/opt/alt/alt-nodejs16/root/usr/lib/node_modules/npm/node_modules.bundled/@npmcli/run-script/lib/run-script.js:9:16)
36 verbose stack     at RunScript.run (/opt/alt/alt-nodejs16/root/usr/lib/node_modules/npm/lib/commands/run-script.js:126:13)
36 verbose stack     at async module.exports (/opt/alt/alt-nodejs16/root/usr/lib/node_modules/npm/lib/cli.js:78:5)
37 verbose cwd /home/mygrsolu/localapp/localapp
38 verbose Linux 3.10.0-962.3.2.lve1.5.68.el7.x86_64
39 verbose node v16.17.1
40 verbose npm  v8.15.0
41 error Cannot read properties of undefined (reading 'stdin')
42 verbose exit 1
43 timing npm Completed in 57ms
44 verbose code 1
45 error A complete log of this run can be found in:
45 error     /home/mygrsolu/.npm/_logs/2023-01-02T16_57_31_192Z-debug-0.log
```

**Comment by nkshah2** [comment]
This seems to be an issue with CENTOS and Node as opposed to with `create-supertokens-app`. Closing as there is nothing to fix here
